I see you've pasted the `prisma/seed.ts` file content. This file has the enum import issue. Let me provide you with the **corrected version** of this file:

---

## 📁 **FILE: prisma/seed.ts** (Corrected)

```typescript
import { PrismaClient } from '@prisma/client';
import {
  Role,
  UserStatus,
  AccountType,
  AccountStatus,
  KYCStatus,
  KYCTier,
  CardType,
  CardBrand,
  CardStatus,
  TransactionType,
  TransactionStatus,
  TransferStatus,
  RiskStatus,
  DepositStatus,
  DepositMethod,
  WithdrawalStatus,
  WithdrawalMethod,
  BeneficiaryStatus,
  FeeType,
  LoanApplicationStatus,
  DisbursementStatus,
  RepaymentStatus,
  PortfolioStatus,
  InvestmentType,
  InvestmentStatus,
  InvestmentTransactionType,
  SavingsGoalStatus,
  ContributionStatus,
  SupportCategory,
  SupportPriority,
  SupportTicketStatus,
  NotificationType,
  NotificationCategory,
  AuditAction,
  ResourceType,
  AuditStatus,
  FraudAlertType,
  FraudAlertStatus,
  SettingCategory,
  JournalStatus
} from '@prisma/client/runtime/library';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  // ============================================
  // PERMISSIONS
  // ============================================
  const permissions = [
    { name: 'user:read', description: 'Read user profiles', category: 'USER' },
    { name: 'user:create', description: 'Create users', category: 'USER' },
    { name: 'user:update', description: 'Update user profiles', category: 'USER' },
    { name: 'user:delete', description: 'Delete users', category: 'USER' },
    { name: 'user:suspend', description: 'Suspend users', category: 'USER' },
    { name: 'user:activate', description: 'Activate users', category: 'USER' },
    { name: 'account:read', description: 'Read accounts', category: 'ACCOUNT' },
    { name: 'account:create', description: 'Create accounts', category: 'ACCOUNT' },
    { name: 'account:freeze', description: 'Freeze accounts', category: 'ACCOUNT' },
    { name: 'account:unfreeze', description: 'Unfreeze accounts', category: 'ACCOUNT' },
    { name: 'account:close', description: 'Close accounts', category: 'ACCOUNT' },
    { name: 'transaction:read', description: 'Read transactions', category: 'TRANSACTION' },
    { name: 'transaction:create', description: 'Create transactions', category: 'TRANSACTION' },
    { name: 'transaction:reverse', description: 'Reverse transactions', category: 'TRANSACTION' },
    { name: 'transfer:read', description: 'Read transfers', category: 'TRANSFER' },
    { name: 'transfer:create', description: 'Create transfers', category: 'TRANSFER' },
    { name: 'transfer:approve', description: 'Approve transfers', category: 'TRANSFER' },
    { name: 'transfer:reject', description: 'Reject transfers', category: 'TRANSFER' },
    { name: 'transfer:reverse', description: 'Reverse transfers', category: 'TRANSFER' },
    { name: 'deposit:read', description: 'Read deposits', category: 'DEPOSIT' },
    { name: 'deposit:create', description: 'Create deposits', category: 'DEPOSIT' },
    { name: 'deposit:approve', description: 'Approve deposits', category: 'DEPOSIT' },
    { name: 'deposit:reject', description: 'Reject deposits', category: 'DEPOSIT' },
    { name: 'withdrawal:read', description: 'Read withdrawals', category: 'WITHDRAWAL' },
    { name: 'withdrawal:create', description: 'Create withdrawals', category: 'WITHDRAWAL' },
    { name: 'withdrawal:approve', description: 'Approve withdrawals', category: 'WITHDRAWAL' },
    { name: 'withdrawal:reject', description: 'Reject withdrawals', category: 'WITHDRAWAL' },
    { name: 'withdrawal:hold', description: 'Place withdrawals on hold', category: 'WITHDRAWAL' },
    { name: 'kyc:read', description: 'Read KYC profiles', category: 'KYC' },
    { name: 'kyc:approve', description: 'Approve KYC', category: 'KYC' },
    { name: 'kyc:reject', description: 'Reject KYC', category: 'KYC' },
    { name: 'kyc:request_info', description: 'Request additional information', category: 'KYC' },
    { name: 'card:read', description: 'Read cards', category: 'CARD' },
    { name: 'card:create', description: 'Create cards', category: 'CARD' },
    { name: 'card:freeze', description: 'Freeze cards', category: 'CARD' },
    { name: 'card:unfreeze', description: 'Unfreeze cards', category: 'CARD' },
    { name: 'card:cancel', description: 'Cancel cards', category: 'CARD' },
    { name: 'loan:read', description: 'Read loans', category: 'LOAN' },
    { name: 'loan:create', description: 'Create loan applications', category: 'LOAN' },
    { name: 'loan:approve', description: 'Approve loans', category: 'LOAN' },
    { name: 'loan:reject', description: 'Reject loans', category: 'LOAN' },
    { name: 'loan:disburse', description: 'Disburse loans', category: 'LOAN' },
    { name: 'fraud:read', description: 'Read fraud alerts', category: 'FRAUD' },
    { name: 'fraud:create', description: 'Create fraud alerts', category: 'FRAUD' },
    { name: 'fraud:review', description: 'Review fraud alerts', category: 'FRAUD' },
    { name: 'fraud:resolve', description: 'Resolve fraud alerts', category: 'FRAUD' },
    { name: 'fraud:escalate', description: 'Escalate fraud alerts', category: 'FRAUD' },
    { name: 'aml:read', description: 'Read AML alerts', category: 'AML' },
    { name: 'aml:review', description: 'Review AML alerts', category: 'AML' },
    { name: 'audit:read', description: 'Read audit logs', category: 'AUDIT' },
    { name: 'audit:export', description: 'Export audit logs', category: 'AUDIT' },
    { name: 'settings:read', description: 'Read settings', category: 'SETTINGS' },
    { name: 'settings:update', description: 'Update settings', category: 'SETTINGS' },
    { name: 'role:read', description: 'Read roles', category: 'ROLE' },
    { name: 'role:assign', description: 'Assign roles', category: 'ROLE' },
    { name: 'role:remove', description: 'Remove roles', category: 'ROLE' },
    { name: 'support:read', description: 'Read support tickets', category: 'SUPPORT' },
    { name: 'support:create', description: 'Create support tickets', category: 'SUPPORT' },
    { name: 'support:assign', description: 'Assign support tickets', category: 'SUPPORT' },
    { name: 'support:resolve', description: 'Resolve support tickets', category: 'SUPPORT' },
    { name: 'support:close', description: 'Close support tickets', category: 'SUPPORT' },
  ];

  const createdPermissions = await Promise.all(
    permissions.map(p => prisma.permission.upsert({
      where: { name: p.name },
      update: p,
      create: p,
    }))
  );
  console.log(`✅ Created ${createdPermissions.length} permissions`);

  const rolePermissions = [
    { role: Role.CUSTOMER, permissionName: 'user:read' },
    { role: Role.CUSTOMER, permissionName: 'account:read' },
    { role: Role.CUSTOMER, permissionName: 'transaction:read' },
    { role: Role.CUSTOMER, permissionName: 'transfer:read' },
    { role: Role.CUSTOMER, permissionName: 'transfer:create' },
    { role: Role.CUSTOMER, permissionName: 'deposit:read' },
    { role: Role.CUSTOMER, permissionName: 'deposit:create' },
    { role: Role.CUSTOMER, permissionName: 'withdrawal:read' },
    { role: Role.CUSTOMER, permissionName: 'withdrawal:create' },
    { role: Role.CUSTOMER, permissionName: 'card:read' },
    { role: Role.CUSTOMER, permissionName: 'kyc:read' },
    { role: Role.CUSTOMER, permissionName: 'loan:read' },
    { role: Role.CUSTOMER, permissionName: 'loan:create' },
    { role: Role.CUSTOMER, permissionName: 'support:read' },
    { role: Role.CUSTOMER, permissionName: 'support:create' },
    { role: Role.SUPPORT, permissionName: 'user:read' },
    { role: Role.SUPPORT, permissionName: 'account:read' },
    { role: Role.SUPPORT, permissionName: 'transaction:read' },
    { role: Role.SUPPORT, permissionName: 'transfer:read' },
    { role: Role.SUPPORT, permissionName: 'deposit:read' },
    { role: Role.SUPPORT, permissionName: 'withdrawal:read' },
    { role: Role.SUPPORT, permissionName: 'card:read' },
    { role: Role.SUPPORT, permissionName: 'kyc:read' },
    { role: Role.SUPPORT, permissionName: 'support:read' },
    { role: Role.SUPPORT, permissionName: 'support:create' },
    { role: Role.SUPPORT, permissionName: 'support:assign' },
    { role: Role.SUPPORT, permissionName: 'support:resolve' },
    { role: Role.SUPPORT, permissionName: 'support:close' },
    { role: Role.SUPPORT, permissionName: 'audit:read' },
    { role: Role.OPERATOR, permissionName: 'user:read' },
    { role: Role.OPERATOR, permissionName: 'user:suspend' },
    { role: Role.OPERATOR, permissionName: 'user:activate' },
    { role: Role.OPERATOR, permissionName: 'account:read' },
    { role: Role.OPERATOR, permissionName: 'account:freeze' },
    { role: Role.OPERATOR, permissionName: 'account:unfreeze' },
    { role: Role.OPERATOR, permissionName: 'transaction:read' },
    { role: Role.OPERATOR, permissionName: 'transaction:reverse' },
    { role: Role.OPERATOR, permissionName: 'transfer:read' },
    { role: Role.OPERATOR, permissionName: 'transfer:approve' },
    { role: Role.OPERATOR, permissionName: 'transfer:reject' },
    { role: Role.OPERATOR, permissionName: 'deposit:read' },
    { role: Role.OPERATOR, permissionName: 'deposit:approve' },
    { role: Role.OPERATOR, permissionName: 'withdrawal:read' },
    { role: Role.OPERATOR, permissionName: 'withdrawal:approve' },
    { role: Role.OPERATOR, permissionName: 'withdrawal:reject' },
    { role: Role.OPERATOR, permissionName: 'withdrawal:hold' },
    { role: Role.OPERATOR, permissionName: 'card:read' },
    { role: Role.OPERATOR, permissionName: 'card:freeze' },
    { role: Role.OPERATOR, permissionName: 'card:unfreeze' },
    { role: Role.OPERATOR, permissionName: 'card:cancel' },
    { role: Role.OPERATOR, permissionName: 'loan:read' },
    { role: Role.OPERATOR, permissionName: 'loan:approve' },
    { role: Role.OPERATOR, permissionName: 'loan:reject' },
    { role: Role.OPERATOR, permissionName: 'loan:disburse' },
    { role: Role.OPERATOR, permissionName: 'fraud:read' },
    { role: Role.OPERATOR, permissionName: 'fraud:review' },
    { role: Role.OPERATOR, permissionName: 'fraud:resolve' },
    { role: Role.OPERATOR, permissionName: 'audit:read' },
    { role: Role.OPERATOR, permissionName: 'support:read' },
    { role: Role.OPERATOR, permissionName: 'support:assign' },
    { role: Role.COMPLIANCE, permissionName: 'user:read' },
    { role: Role.COMPLIANCE, permissionName: 'user:suspend' },
    { role: Role.COMPLIANCE, permissionName: 'kyc:read' },
    { role: Role.COMPLIANCE, permissionName: 'kyc:approve' },
    { role: Role.COMPLIANCE, permissionName: 'kyc:reject' },
    { role: Role.COMPLIANCE, permissionName: 'kyc:request_info' },
    { role: Role.COMPLIANCE, permissionName: 'aml:read' },
    { role: Role.COMPLIANCE, permissionName: 'aml:review' },
    { role: Role.COMPLIANCE, permissionName: 'fraud:read' },
    { role: Role.COMPLIANCE, permissionName: 'fraud:review' },
    { role: Role.COMPLIANCE, permissionName: 'fraud:escalate' },
    { role: Role.COMPLIANCE, permissionName: 'audit:read' },
    { role: Role.COMPLIANCE, permissionName: 'audit:export' },
    { role: Role.COMPLIANCE, permissionName: 'transaction:read' },
    { role: Role.COMPLIANCE, permissionName: 'account:read' },
  ];

  for (const rp of rolePermissions) {
    const permission = createdPermissions.find(p => p.name === rp.permissionName);
    if (permission) {
      await prisma.rolePermission.upsert({
        where: {
          role_permissionId: {
            role: rp.role,
            permissionId: permission.id,
          },
        },
        update: {},
        create: {
          role: rp.role,
          permissionId: permission.id,
        },
      });
    }
  }
  console.log(`✅ Created ${rolePermissions.length} role permissions`);

  const password = await bcrypt.hash('Demo@123456', 12);
  const adminPassword = await bcrypt.hash('Admin@123456', 12);
  const compliancePassword = await bcrypt.hash('Compliance@123', 12);

  const users = [
    {
      email: 'john.doe@crestline.capital',
      password,
      firstName: 'John',
      lastName: 'Doe',
      phone: '+1234567890',
      dateOfBirth: new Date('1985-05-15'),
      address: '123 Main St',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'US',
      status: UserStatus.ACTIVE,
      role: Role.CUSTOMER,
      emailVerified: true,
      phoneVerified: true,
    },
    {
      email: 'jane.smith@crestline.capital',
      password,
      firstName: 'Jane',
      lastName: 'Smith',
      phone: '+1987654321',
      dateOfBirth: new Date('1990-08-20'),
      address: '456 Oak Ave',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90001',
      country: 'US',
      status: UserStatus.ACTIVE,
      role: Role.CUSTOMER,
      emailVerified: true,
      phoneVerified: true,
    },
    {
      email: 'admin@crestline.capital',
      password: adminPassword,
      firstName: 'Admin',
      lastName: 'User',
      phone: '+1111111111',
      dateOfBirth: new Date('1980-01-01'),
      address: '789 Admin Blvd',
      city: 'Chicago',
      state: 'IL',
      zipCode: '60601',
      country: 'US',
      status: UserStatus.ACTIVE,
      role: Role.ADMIN,
      emailVerified: true,
      phoneVerified: true,
    },
    {
      email: 'compliance@crestline.capital',
      password: compliancePassword,
      firstName: 'Compliance',
      lastName: 'Officer',
      phone: '+1222222222',
      dateOfBirth: new Date('1975-03-10'),
      address: '321 Compliance St',
      city: 'Washington',
      state: 'DC',
      zipCode: '20001',
      country: 'US',
      status: UserStatus.ACTIVE,
      role: Role.COMPLIANCE,
      emailVerified: true,
      phoneVerified: true,
    },
    {
      email: 'support@crestline.capital',
      password,
      firstName: 'Support',
      lastName: 'Agent',
      phone: '+1333333333',
      dateOfBirth: new Date('1988-11-25'),
      address: '654 Support Ave',
      city: 'Miami',
      state: 'FL',
      zipCode: '33101',
      country: 'US',
      status: UserStatus.ACTIVE,
      role: Role.SUPPORT,
      emailVerified: true,
      phoneVerified: true,
    },
    {
      email: 'operator@crestline.capital',
      password,
      firstName: 'Operator',
      lastName: 'Staff',
      phone: '+1444444444',
      dateOfBirth: new Date('1992-07-14'),
      address: '987 Operator Ln',
      city: 'Houston',
      state: 'TX',
      zipCode: '77001',
      country: 'US',
      status: UserStatus.ACTIVE,
      role: Role.OPERATOR,
      emailVerified: true,
      phoneVerified: true,
    },
  ];

  const createdUsers = await Promise.all(
    users.map(u => prisma.user.upsert({
      where: { email: u.email },
      update: u,
      create: u,
    }))
  );
  console.log(`✅ Created ${createdUsers.length} users`);

  const johnDoe = createdUsers.find(u => u.email === 'john.doe@crestline.capital')!;
  const janeSmith = createdUsers.find(u => u.email === 'jane.smith@crestline.capital')!;
  const admin = createdUsers.find(u => u.email === 'admin@crestline.capital')!;

  const accounts = [
    {
      userId: johnDoe.id,
      accountNumber: 'CL-001-000001',
      accountType: AccountType.CHECKING,
      name: 'Primary Checking',
      currency: 'USD',
      status: AccountStatus.ACTIVE,
      balance: 10000.00,
      availableBalance: 10000.00,
    },
    {
      userId: johnDoe.id,
      accountNumber: 'CL-001-000002',
      accountType: AccountType.SAVINGS,
      name: 'Savings Account',
      currency: 'USD',
      status: AccountStatus.ACTIVE,
      balance: 5000.00,
      availableBalance: 5000.00,
    },
    {
      userId: janeSmith.id,
      accountNumber: 'CL-002-0000